services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=database'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=supersecretpassword1'
    ports:
      - '5432:5432'